# ruff: noqa: I001,E402
"""Parsing an editable CSV and save its markdown and ProcessedDocument output (generated by copilot and arranged a little)."""

import argparse
import asyncio
import csv
from pathlib import Path
from _bootstrap import ensure_openrag_source_path
ensure_openrag_source_path() # really useful for running this script from the examples directory
from core.indexing.parsers.tabular.csv_parser import CsvParser
from core.models.document import Document


async def main():
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument("file", type=Path, help="CSV file to read (never modified)")
    cli.add_argument("--delimiter", default=",", help="Cell separator; default: comma")
    args = cli.parse_args()
    if args.file.suffix.lower() != ".csv":
        cli.error("Choose a file ending in .csv")
    if len(args.delimiter) != 1:
        cli.error("The delimiter must be one character")
    document = Document(source_path=str(args.file), metadata={"source": args.file.name})
    try:
        result = await CsvParser(delimiter=args.delimiter).parse(document)
    except (OSError, ValueError, csv.Error) as error:
        cli.exit(1, f"Parsing failed: {error}\nNo new output was written; any previous output is unchanged.\n")

    # extract the readable table from the actual ProcessedDocument
    markdown = "\n\n".join(block.text for block in result.text_blocks)
    markdown_path = args.file.with_suffix(".parsed.md")
    json_path = args.file.with_suffix(".parsed.json")
    markdown_path.write_text(markdown, encoding="utf-8")
    json_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    print(markdown or "(Empty CSV: no text blocks)")
    print(f"\nMarkdown: {markdown_path}")
    print(f"Full parser result: {json_path}")


if __name__ == "__main__":
    asyncio.run(main())
